name = "RimuLegacyHamiltonians"
uuid = "ab007b36-820d-4a5f-9ad7-658c1a52e218"
authors = ["Joachim Brand <joachim.brand@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Rimu = "c53c40cc-bd84-11e9-2cf4-a9fde2b9386e"

[compat]
Rimu = "0.13, 0.14"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
