name = "RimuLegacyHamiltonians"
uuid = "ab007b36-820d-4a5f-9ad7-658c1a52e218"
authors = ["Joachim Brand <joachim.brand@gmail.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.9"

[targets]
test = ["Test"]
