name: Run tests

on:
  push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1', 'nightly', '1.9']
        os: [ubuntu-latest]
        include:
          - julia-version: '1'
            os: macos-latest
      fail-fast: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: "Load cache"
        uses: julia-actions/cache@v2
      - name: "Build"
        uses: julia-actions/julia-buildpkg@v1
      - name: "Run tests"
        run: |
          julia --color=yes --project=@. -t2 -e "using Pkg; Pkg.test(\"RimuLegacyHamiltonians\"; coverage=true);"

      - name: "Process coverage"
        uses: julia-actions/julia-processcoverage@v1
      - name: "Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./lcov.info
        if: ${{ matrix.julia-version == '1' }}
